AWSTemplateFormatVersion: '2010-09-09'
Description: SNS Topic with Email Subscription and Filter Policy

Parameters:
  EmailAddress:
    Type: String
    Description: Email address for SNS subscription

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: TestFilterPolicyTopic

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopic
      Protocol: email
      Endpoint: !Ref EmailAddress # Replace with your email
      FilterPolicy:
        Pause:
          - "True"
      FilterPolicyScope: MessageAttributes

Outputs:
  TopicARN:
    Description: ARN of the SNS Topic
    Value: !Ref SNSTopic