AWSTemplateFormatVersion: 2010-09-09
Description: > 
  This CloudFormation Template will create the following:
  - A launch template requiring IMDSv2
  - A security group that allows inbound ICMP, RDP and WinRM from 10.0.0.0/8, and outbound to all traffic in 10.0.0.0/8
  - A Windows EC2 using latest Windows Server 2022 AMI

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.medium
      - t3.large
    Description: EC2 instance type
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: KeyPair for Windows instances
  LatestWindows2022AMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-windows-latest/Windows_Server-2022-English-Full-Base

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for the EC2 instance
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Target subnet ID for the EC2 instance

Resources:
  WindowsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Windows instance allowing RDP and WinRM
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 10.0.0.0/8
        - IpProtocol: tcp
          FromPort: 5985
          ToPort: 5986
          CidrIp: 10.0.0.0/8
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 10.0.0.0/8
      SecurityGroupEgress:
        - IpProtocol: "-1"
          FromPort: -1
          ToPort: -1
          CidrIp: 10.0.0.0/8

  # New IAM Instance Profile referencing the existing role
  SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - AmazonSSMRoleForInstancesQuickSetup  # Ensure this role exists in your account

  WindowsEC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref LatestWindows2022AMI
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyPairName
        MetadataOptions:
          HttpTokens: required
          HttpEndpoint: enabled
          InstanceMetadataTags: enabled
        # Attach the IAM Instance Profile
        IamInstanceProfile:
          Arn: !GetAtt SSMInstanceProfile.Arn
        NetworkInterfaces:
          - DeviceIndex: 0
            SubnetId: !Ref SubnetId
            AssociatePublicIpAddress: false
            Groups:
              - !GetAtt WindowsSecurityGroup.GroupId
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 30
              VolumeType: gp3
              DeleteOnTermination: true
              Encrypted: true

  WindowsEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref WindowsEC2LaunchTemplate
        Version: !GetAtt WindowsEC2LaunchTemplate.LatestVersionNumber

Outputs:
  InstanceId:
    Description: Windows EC2 Instance ID
    Value: !Ref WindowsEC2Instance
  SecurityGroupId:
    Description: Created Security Group ID
    Value: !GetAtt WindowsSecurityGroup.GroupId

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: EC2 Configuration
        Parameters:
          - InstanceType
          - KeyPairName
          - LatestWindows2022AMI
      - Label:
          default: Network Configuration
        Parameters:
          - VpcId 
          - SubnetID
    ParameterLabels:
      InstanceType:
        default: Instance Type
      KeyName:
        default: Key Pair Name
      SubnetID:
        default: Target Subnet